### ISSUE TITLE
unmarshall the CID content

### ISSUE THREAD

**Issue by eckelj** [rddl-network/tendermint-explorer#26]
The CID page shows the marshalled CID data. In python the ipld - marshal method is used. 
we need to identify the corresponding JS method to unmarshal the data.

**Comment by jmastr** [comment]
unmarshalling from python;
```
from ipld import unmarshal
f = open("/home/julian/Downloads/download", "rb")
unmarshalled_asset = unmarshal(f.read())
print(unmarshalled_asset)
```
with: https://bafkreiftyhhknkdvbjjlr5n55sjnekpr7kkvwzekoekk2figxk3lp7ta5y.ipfs.w3s.link/
```
from ipld import unmarsha

l
f = open("/home/julian/Downloads/download", "rb")
unmarshalled_asset = unmarshal(f.read())
print(unmarshalled_asset)
```

**Comment by jmastr** [comment]
I stumbled upon this: https://github.com/ipld/js-ipld and it's successor: https://github.com/multiformats/js-multiformats/tree/v9.5.3 

Both are not implementing the unmarshal method from py-ipld.

@eckelj can we switch to another serialization method?

**Comment by jmastr** [comment]
From standup: try to to use raw/json data directly for creating the ipfs hash

**Comment by jmastr** [comment]
Alternative: use the cid-resolver for unmarshalling

**Comment by jmastr** [comment]
This example from the official CID Inspector https://cid.ipfs.tech/#bafybeigrf2dwtpjkiovnigysyto3d55opf6qkdikx6d65onrqnfzwgdkfa shows that there is image data behind the CID: https://bafybeigrf2dwtpjkiovnigysyto3d55opf6qkdikx6d65onrqnfzwgdkfa.ipfs.dweb.link/

So chances are we can use JSON directly.
